name: Pipelineworkflow

on:
  push:
    branches:
    - newbranch

jobs:
  build:
    name: Azure pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/levapfilingeri/DevProject1'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        azure-pipeline-name: 'pavelux00x.xUnitEST'
        # Add test commands here


